//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package hophophop.commun.vue;

import javax.swing.Icon;
import javax.swing.ImageIcon;

public abstract class Icones {
    private static final String REPERTOIRE_ICONES = "hophophop/commun/vue/icones/";
    private static final String REPERTOIRE_ICONES_16 = "hophophop/commun/vue/icones/16x16/";
    private static final String REPERTOIRE_ICONES_32 = "hophophop/commun/vue/icones/32x32/";
    private static final String REPERTOIRE_ICONES_48 = "hophophop/commun/vue/icones/48x48/";
    private static final String REPERTOIRE_ICONES_64 = "hophophop/commun/vue/icones/64x64/";
    private static final String REPERTOIRE_ICONES_128 = "hophophop/commun/vue/icones/128x128/";
    private static final String REPERTOIRE_ECLIPSE = "hophophop/commun/vue/icones/Eclipse/";
    public static final Icon HOP3X_128;
    public static final Icon ETUDIANT_128;
    public static final Icon SERVEUR_128;
    public static final Icon TUTEUR_128;
    public static final Icon ECLIPSE_VI_PRIVEE;
    public static final Icon ECLIPSE_VI_PUBLIC;
    public static final Icon ECLIPSE_VI_PROTECTED;
    public static final Icon ECLIPSE_VI_DEFAUT;
    public static final Icon ECLIPSE_METHODE_PRIVEE;
    public static final Icon ECLIPSE_METHODE_PUBLIC;
    public static final Icon ECLIPSE_METHODE_PROTECTED;
    public static final Icon CARRE_VERT_16;
    public static final Icon CARRE_ROUGE_16;
    public static final Icon QUITTER_16;
    public static final Icon OK_16;
    public static final Icon ANNULER_16;
    public static final Icon GOMME_32;
    public static final Icon CLIENT_16;
    public static final Icon UTILISATEUR_16;
    public static final Icon SESSION_16;
    public static final Icon DEMARRER_16;
    public static final Icon ARRIERE_16;
    public static final Icon ARRETER_16;
    public static final Icon PREFERENCES_16;
    public static final Icon AJOUTER_16;
    public static final Icon SUPPRIMER_16;
    public static final Icon SUPPRIMER_DOSSIER_32;
    public static final Icon SUPPRIMER_FICHIER_32;
    public static final Icon PRECEDENT_16;
    public static final Icon SUIVANT_16;
    public static final Icon CONNECTER_16;
    public static final Icon DECONNECTER_16;
    public static final Icon A_PROPOS_16;
    public static final Icon PAUSE_16;
    public static final Icon IMPORTER_16;
    public static final Icon FERMER_16;
    public static final Icon FERMER_TOUT_16;
    public static final Icon NOUVEAU_PROJET_16;
    public static final Icon NOUVEAU_PROJET_32;
    public static final Icon MESSAGE_USER_32;
    public static final Icon MESSAGE_ALL_32;
    public static final Icon NOUVEAU_FICHIER_16;
    public static final Icon NOUVEAU_FICHIER_32;
    public static final Icon COMPILER_16;
    public static final Icon COMPILER_32;
    public static final Icon TERMINAL_32;
    public static final Icon EXECUTER_32;
    public static final Icon ENREGISTRER_16;
    public static final Icon ENREGISTRER_TOUT_16;
    public static final Icon COUPER_16;
    public static final Icon COUPER_32;
    public static final Icon COPIER_16;
    public static final Icon COPIER_32;
    public static final Icon COLLER_16;
    public static final Icon COLLER_32;
    public static final Icon DOCUMENTATION_16;
    public static final Icon SELECTIONNER_TOUT_16;
    public static final Icon SELECTIONNER_TOUT_32;
    public static final Icon RECHERCHE_AVANT_32;
    public static final Icon RECHERCHE_ARRIERE_32;
    public static final Icon REMPLACE_32;
    public static final Icon OUVRIR_PROJET_16;
    public static final Icon FICHIER_16;
    public static final Icon PROJET_16;
    public static final Icon DOSSIER_16;
    public static final Icon EXPLORATEUR_16;
    public static final Icon EDITEUR_16;
    public static final Icon CONSOLE_16;
    public static final Icon CONTROLEUR_16;
    public static final Icon TEMPS_16;
    public static final Icon CLASSE_16;
    public static final Icon INTERFACE_16;
    public static final Icon ETUDIANT_16;
    public static final Icon ENSEIGNANT_16;
    public static final Icon SERVEUR_16;
    public static final Icon ERREUR_32;
    public static final Icon QUITTER_32;
    public static final Icon SESSION_32;
    public static final Icon PREFERENCES_32;
    public static final Icon DECONNECTER_32;
    public static final Icon FICHIER_32;
    public static final Icon CONNECTER_32;
    public static final Icon ENREGISTRER_32;
    public static final Icon PROJET_32;
    public static final Icon IMPORTER_32;
    public static final Icon DEMARRER_32;
    public static final Icon INFO_64;
    public static final Icon FLECHESGAUCHES_32;
    public static final Icon FLECHESDROITES_32;
    public static final Icon FLECHESGAUCHES_24;
    public static final Icon FLECHESDROITES_24;
    public static final Icon FLECHESGAUCHES_16;
    public static final Icon FLECHESDROITES_16;
    public static final Icon RESTAURER_32;
    public static final Icon ASSISTANCE_32;
    public static final Icon ARGUMENTS_32;
    public static final Icon MONTRERHISTORIQUE_32;
    public static final Icon GLADE_32;
    public static final Icon UNDO_32;
    public static final Icon REDO_32;
    public static final Icon UTILISATEUR_32;
    public static final Icon PASSWORDETUDIANT_32;
    public static final Icon TUTEUR_32;
    public static final Icon UTILISATEUR_48;
    public static final Icon CHOIXSESSION_48;
    public static final Icon CHOIXSESSION_32;
    public static final Icon COMMENTE_32;
    public static final Icon DECOMMENTE_32;
    public static final Icon SIMULATEUR_32;
    public static final Icon ROBOT_32;
    public static final Icon TEST_UNITAIRE_32;
    public static final Icon CARRE_BLANC_16;
    public static final Icon JITSI_32;
    public static final Icon PARSER_32;
    public static final Icon PASDETRACE;
    public static final Icon TRACE_32;
    public static final Icon DOCUMENT_32;
    public static final Icon DOCUMENTS_32;

    public Icones() {
    }

    static {
        ClassLoader loader = Icones.class.getClassLoader();
        DOCUMENT_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/document32.png"));
        DOCUMENTS_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/documents32.png"));
        TRACE_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/trace-32.png"));
        PASDETRACE = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/PasdeTrace.png"));
        MESSAGE_ALL_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/message-all-32.png"));
        MESSAGE_USER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/message-user-32.png"));
        CARRE_BLANC_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/carre_blanc_16.png"));
        CARRE_VERT_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/carre_vert_16.png"));
        CARRE_ROUGE_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/carre_rouge_16.png"));
        HOP3X_128 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/128x128/Hop3x128.png"));
        ETUDIANT_128 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/128x128/Hop3xEtudiant128.png"));
        SERVEUR_128 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/128x128/Hop3xServeur128.png"));
        TUTEUR_128 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/128x128/Hop3xTuteur128.png"));
        ECLIPSE_VI_PRIVEE = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/Eclipse/eclipse-field_private_obj.gif"));
        ECLIPSE_VI_PUBLIC = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/Eclipse/eclipse-field_public_obj.gif"));
        ECLIPSE_VI_PROTECTED = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/Eclipse/eclipse-field_protected_obj.gif"));
        ECLIPSE_VI_DEFAUT = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/Eclipse/eclipse-field_default_obj.gif"));
        ECLIPSE_METHODE_PRIVEE = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/Eclipse/eclipse-methpri_obj.gif"));
        ECLIPSE_METHODE_PUBLIC = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/Eclipse/eclipse-methpub_obj.gif"));
        ECLIPSE_METHODE_PROTECTED = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/Eclipse/eclipse-methpro_obj.gif"));
        JITSI_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/jtsi-32.png"));
        TEST_UNITAIRE_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/test_unitaire_32.png"));
        SIMULATEUR_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/simulateur-32.png"));
        ROBOT_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/robot-32.png"));
        PARSER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/search-icon.png"));
        MONTRERHISTORIQUE_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/historiqueMessage-32.png"));
        RESTAURER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/restaurer-32.png"));
        ASSISTANCE_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/demander-aide-32.png"));
        ARGUMENTS_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/runarg.png"));
        QUITTER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/quitter.png"));
        QUITTER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/sortir-session-32.png"));
        GOMME_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/gomme32.png"));
        OK_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/accepter-16.png"));
        ANNULER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/annuler-16.png"));
        UNDO_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/undo-32.png"));
        REDO_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/redo-32.png"));
        CLIENT_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/client.png"));
        UTILISATEUR_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/utilisateur-16.png"));
        UTILISATEUR_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/utilisateur-32.png"));
        PASSWORDETUDIANT_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/passwordEtudiant_32.png"));
        TUTEUR_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/utilisateurTuteur-32.png"));
        UTILISATEUR_48 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/48x48/utilisateur-48.png"));
        CHOIXSESSION_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/choixSession-32.png"));
        CHOIXSESSION_48 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/48x48/choixSession-48.png"));
        COMMENTE_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/commente-32.png"));
        DECOMMENTE_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/decommente-32.png"));
        SESSION_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/choixSession-16.png"));
        DEMARRER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/demarrer.png"));
        ARRIERE_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/arriere.png"));
        ARRETER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/arreter.png"));
        TEMPS_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/temps.png"));
        PREFERENCES_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/preferences.png"));
        CONTROLEUR_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/controleur.png"));
        CONSOLE_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/console.png"));
        EDITEUR_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/editeur.png"));
        EXPLORATEUR_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/explorateur.png"));
        PROJET_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/projet.png"));
        DOSSIER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/dossier-16.png"));
        FICHIER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/fichier.png"));
        NOUVEAU_PROJET_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/nouveau_projet.png"));
        NOUVEAU_FICHIER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/nouveau_fichier.png"));
        NOUVEAU_PROJET_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/ajouter-dossier-32.png"));
        NOUVEAU_FICHIER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/ajouter-fichier-32.png"));
        EXECUTER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/executer-32.png"));
        RECHERCHE_AVANT_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/RechercheAvant-32.png"));
        RECHERCHE_ARRIERE_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/RechercheArriere-32.png"));
        REMPLACE_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/remplacer-32.png"));
        COUPER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/couper.png"));
        COLLER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/coller.png"));
        COPIER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/copier.png"));
        COUPER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/editcut-32.png"));
        COLLER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/editpaste-32.png"));
        COPIER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/editcopy-32.png"));
        DOCUMENTATION_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/documentation.png"));
        OUVRIR_PROJET_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/ouvrir_projet.png"));
        SELECTIONNER_TOUT_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/selectionner_tout.png"));
        SELECTIONNER_TOUT_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/editselect-all-32.png"));
        ENREGISTRER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/enregistrer.png"));
        ENREGISTRER_TOUT_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/enregistrer_tout.png"));
        FERMER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/fermer.png"));
        FERMER_TOUT_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/fermer_tout.png"));
        COMPILER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/compiler.png"));
        COMPILER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/compiler-32.png"));
        PRECEDENT_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/precedent.png"));
        SUIVANT_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/suivant.png"));
        SUPPRIMER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/supprimer.png"));
        SUPPRIMER_FICHIER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/supprimer-fichier-32.png"));
        SUPPRIMER_DOSSIER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/supprimer-projet-32.png"));
        AJOUTER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/ajouter.png"));
        CONNECTER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/connecter.png"));
        DECONNECTER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/deconnecter.png"));
        PAUSE_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/pause.png"));
        A_PROPOS_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/a_propos.png"));
        IMPORTER_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/importer.png"));
        CLASSE_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/fichier-16.png"));
        INTERFACE_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/interface.png"));
        ETUDIANT_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/h3etu.png"));
        ENSEIGNANT_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/h3ens.png"));
        SERVEUR_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/16x16/h3srv.png"));
        GLADE_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/glade-32.png"));
        ERREUR_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/erreur.png"));
        SESSION_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/session.png"));
        PREFERENCES_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/preferences.png"));
        DECONNECTER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/deconnecter.png"));
        FICHIER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/fichier.png"));
        CONNECTER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/connecter.png"));
        ENREGISTRER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/enregistrer.png"));
        PROJET_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/projet.png"));
        IMPORTER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/importer.png"));
        DEMARRER_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/demarrer.png"));
        FLECHESGAUCHES_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/2leftarrow.png"));
        FLECHESDROITES_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/2rightarrow.png"));
        FLECHESGAUCHES_24 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/2leftarrow_24.png"));
        FLECHESDROITES_24 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/2rightarrow_24.png"));
        FLECHESGAUCHES_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/2leftarrow_16.png"));
        FLECHESDROITES_16 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/2rightarrow_16.png"));
        TERMINAL_32 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/32x32/terminal-32.png"));
        INFO_64 = new ImageIcon(loader.getResource("hophophop/commun/vue/icones/64x64/information-64.png"));
    }
}
